### ISSUE TITLE
Complex rendering failure - dashboard light

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#109]
Silverlight renders this:
![capture](https://cloud.githubusercontent.com/assets/2708028/7914794/3085b0b8-0847-11e5-97ea-9130a0a03dcc.PNG)

Fayde renders this:
![capture2](https://cloud.githubusercontent.com/assets/2708028/7914809/51c821ca-0847-11e5-948d-1764758aca3e.PNG)

Will add a testsite case shortly.

**Comment by BSick7** [comment]
RadialGradientBrush needs to be implemented

**Comment by BSick7** [comment]
RadialGradientBrush was implemented with 0.16.26.

**Comment by BSick7** [comment]
Panel zsorting was arbitrarily reordering if elements did not have `Panel.ZIndex`.  Fixed in minerva 0.4.11.  Fayde 0.16.29 requires minimum version 0.4.11.

**Comment by BSick7** [comment]
It appears the `Rectangle.RadiusX`/`Rectangle.RadiusY` is acting differently for the glowing red center.

**Comment by asthomas** [comment]
This is much improved.  I can see all of the parts now.  On my system I still see the three fly-away highlights that should be along the bottom border of the light.

**Comment by BSick7** [comment]
Rectangle was using quadratic bezier curves to build rounded corners.  Silverlight Rectangle uses elliptical arcs. Currently switching @ https://github.com/wsick/minerva/tree/fix-rounded-rect.  This is only implemented in Chrome/Opera so I still need to build a polyfill for `ctx.ellipse(...)` for IE/Safari/Firefox.

**Comment by BSick7** [comment]
In an attempt to simplify and speed up Paths from Silverlight, I took some shortcuts.  The 3 offending paths are using `Stretch="Fill"`.

I am going to track this as a separate issue #117.

**Comment by BSick7** [comment]
Closing issue as stretching issue will be resolved with #117.
